name: "MetaCall Distributable Windows Release"

on:
  pull_request:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
  workflow_dispatch:
    # TODO: Implement support to automatically update the version of
    # metacall/core when there is a tag on that repo that triggers this one
    inputs:
      ref:
        description: "Version of metacall/core that triggered this workflow"
        required: false
        default: ""

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Build
        shell: powershell
        run: .\build.bat

      - name: Test
        shell: powershell
        run: .\test.bat

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: metacall-tarball-win-x64.zip
          fail_on_unmatched_files: true

  trigger:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Trigger Install Test Workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: metacall
          repo: install
          github_token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: test-windows.yml
          wait_workflow: true
          ref: master
